
services:
  homeassistant:
    build: ./homeassistant
    ports:
      - 8123:8123
    volumes:
      - ./volumes/ha-config:/config
  ocserv:
    build: ./ocserv
    ports:
      - 443:443
    volumes:
      - ./volumes/ocserv/conf:/ocserv/conf
      - /etc/letsencrypt/archive:/cert
    sysctls:
      - net.ipv4.ip_forward=1
    cap_add:
      - NET_ADMIN
