
services:
  homeassistant:
    build: ./homeassistant
    ports:
      - 8123:8123
    volumes:
      - ./volumes/ha-config:/config
  tor:
    build: ./tor
    volumes:
      - ./volumes/tor:/config
  i2pd:
    build: ./i2pd
    volumes:
      - ./volumes/i2pd:/home/i2pd
  privoxy:
    build: ./privoxy
    ports:
      - 8118:8118
    volumes:
      - ./volumes/privoxy:/config/
  ocserv:
    build: ./ocserv
    ports:
      - 443:443
    volumes:
      - ./volumes/ocserv/conf:/ocserv/conf
      - /etc/letsencrypt/archive:/cert
    sysctls:
      - net.ipv4.ip_forward=1
    cap_add:
      - NET_ADMIN
