services:
  certbot:
    build: ./certbot
    ports:
      - 80:80
    volumes:
      - ./volumes/certbot:/certbot/data
    deploy:
      resources:
        limits:
          memory: 32M
        reservations:
          memory: 16M
  ocserv:
    build: ./ocserv
    ports:
      - 443:443
    volumes:
      - ./volumes/ocserv/conf:/ocserv/conf
      - ./volumes/certbot/config/archive:/cert
    depends_on:
      certbot:
        condition: service_completed_successfully    
    deploy:
      resources:
        limits:
          memory: 32M
        reservations:
          memory: 16M
    sysctls:
      - net.ipv4.ip_forward=1
    cap_add:
      - NET_ADMIN
  homeassistant:
    build: ./homeassistant
    ports:
      - 8123:8123
    volumes:
      - ./volumes/ha-config:/config
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
  tor:
    build: ./tor
    volumes:
      - ./volumes/tor:/config
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
  i2pd:
    build: ./i2pd
    volumes:
      - ./volumes/i2pd:/home/i2pd
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
  privoxy:
    build: ./privoxy
    ports:
      - 8118:8118
    volumes:
      - ./volumes/privoxy:/config/
    deploy:
      resources:
        limits:
          memory: 16M
        reservations:
          memory: 8M
